---
title: "Task 1 Markdown File"
author: "Group 3"
date: "4/15/2018"
output: html_document
---

# ECON 386 - Group 3 - Data Cleaning Project - Task 1

Ensure the dplyr and tidyr libraries are installed. [Matt/Nikki]
```
install.packages("dplyr")
install.packages("tidyr")
```


Ensure the dplyr and tidyr libraries have been called. [Matt/Nikki]
```
library(dplyr)
library(tidyr)
```


Set the working directory to the folder of choice, which contains the relevant raw data files provided for this project. [Matt/Nikki]
```
setwd("INSERT YOUR DIRECTORY FILEPATH HERE")
```


Assign tbl_df names and import the relevant text files into R Studio converted to tbl_df format. [Nikki/Matthew/Matt]
```
test_data <-tbl_df(read.table("X_test.txt"))
train_data <-tbl_df(read.table("X_train.txt"))
test_labels <-tbl_df(read.table("Y_test.txt"))
train_labels <-tbl_df(read.table("Y_train.txt"))
activities <-tbl_df(read.table("activity_labels.txt"))
variable_names <-tbl_df(read.table("features.txt"))
test_subject <-tbl_df(read.table("subject_test.txt"))
train_subject <-tbl_df(read.table("subject_train.txt"))
```


Bind the testing and training rows for the subjects, labels, and data, respectively. [Nikki]
```
subjects <-bind_rows(test_subject, train_subject)
labels <-bind_rows(test_labels, train_labels)
data <-bind_rows(test_data, train_data)
```


Change the column names of subjects, labels, and data, respectively. [Matt]
```
colnames(subjects)[1]<-"Subject"
colnames(labels)[1]<-"Activity"
variable_names<-variable_names$V2
```


Remove the first column of "variable_names" which is unnecessary. [Matthew]
```
variable_names <-as.character(variable_names)
```


Change the format of "variable_names" to characters, so it can replace the column names of "data". [Matthew]
```
colnames(data)[1:561]<-variable_names
```


Combine subjects, labels, and data to create the full dataset. [Nikki/Matthew/Matt]
```
fulldata <- bind_cols(subjects, labels, data)
```


Use dplyr chain to select the correct features (only means and standard deviations), group by subject and activity, and compute group averages [Matthew]
```
final_data<-fulldata%>%
  select(matches('Subject|Activity|mean|std'), -contains("angle"))%>%
  group_by(Subject, Activity)%>%
  summarize_all(funs(mean))
```


Change activity names from numbers to descriptive labels.[Nikki]
```
final_data$Activity[final_data$Activity =="1"] <- "WALKING"
final_data$Activity[final_data$Activity =="2"] <- "WALKING_UPSTAIRS"
final_data$Activity[final_data$Activity =="3"] <- "WALKING_DOWNSTAIRS"
final_data$Activity[final_data$Activity =="4"] <- "SITTING"
final_data$Activity[final_data$Activity =="5"] <- "STANDING"
final_data$Activity[final_data$Activity =="6"] <- "LAYING"
```


Save the final dataset as tidy1.txt [Nikki/Matthew/Matt]
```
write.table(final_data, "tidy1.txt", row.names = F, quote = F)
```





